---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  products:
    default_front_matter_template: products
upload_dir: snipcart-hugo-demo
public_path: "/snipcart-hugo-demo"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.38.1
